#cd /Users/hanjinbo/Documents/xiaoke/公司项目/迎园地理课/YingYuanGeography
#pod install --verbose --no-repo-update
target ‘YingYuanGeography’ do
    inhibit_all_warnings!         #禁止所有警告
    #  pod 'pop', :git => 'https://github.com/facebook/pop.git'
    #  pod 'MLTransition', '~> 2.1.2'#滑动返回
    pod 'AFNetworking'  #网络请求
    #  pod 'Canvas', '~> 0.1.2'      #动画
    #  pod 'KMCGeigerCounter'        #检测app fps是否流畅 左边值越大越不流畅
    #  pod 'ResearchKit', '~> 1.3.1' #苹果官方的医疗SKD
    #  pod 'ReactiveObjC', '~> 3.0.0'#链式编程
    #  pod 'Bugly'                   #腾讯bug管理系统
    pod 'MJExtension'             #MJ的字典模型互转
    #    pod 'Masonry'                 #自动适配
    #  pod 'GPUImage', '~> 0.1.7'    #图形处理
    pod 'ChameleonFramework'         #变色龙颜色处理
    #  pod 'YYCache'                 #离线缓存
    pod 'Tweaks'                 #开发时，参数微调使用
    pod 'iCarousel'                #轮播效果类库
    pod 'IQKeyboardManager'                #自动键盘
    #    pod 'CocoaLumberjack'   #log日志记录
    pod 'FBMemoryProfiler' #facebook 内存和循环引用监测
    #    pod 'SVProgressHUD' #提示框，用法简洁高效，ios7兼容性有问题，不显示
    pod 'MBProgressHUD' #提示框，用法复杂一点，定制化多一点
    pod 'QRCodeReaderViewController' #二维码扫描控件
    pod 'YYImage'
end
